name: config

on:
  workflow_call:
    inputs:
      registry_uri:
        description: 'Artifact Registry URI'
        required: true
        type: string
      project_id:
        description: 'ID of the GCP project'
        required: true
        type: string
      registry_image:
        description: 'Name of the image with registry'
        required: true
        type: string
      id_provider:
        description: 'OIDC provider'
        required: true
        type: string
      service_account:
        description: 'Email of the service account to use with OIDC provider'
        required: true
        type: string
      kms_key:
        required: true
        description: 'KMS key path'
        type: string
      go_version:
        description: 'Version og Go to use for tests'
        default: ^1.19.4
        required: false
        type: string
      cosign_version:
        description: 'Version of Cosign to use for signing'
        default: v1.13.1
        required: false
        type: string
    outputs:
      registry_uri:
        value: ${{ jobs.conf.outputs.registry_uri }}
      image_uri:
        value: ${{ jobs.conf.outputs.image_uri }}
      id_provider:
        value: ${{ jobs.conf.outputs.id_provider }}
      service_account:
        value: ${{ jobs.conf.outputs.service_account }}
      kms_key:
        value: ${{ jobs.conf.outputs.kms_key }}

jobs:

  conf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      registry_uri: ${{ steps.conf.outputs.registry_uri }}
      image_uri: ${{ steps.conf.outputs.image_uri }}
      id_provider: ${{ steps.conf.outputs.id_provider }}
      service_account: ${{ steps.conf.outputs.service_account }}
      kms_key: ${{ steps.conf.outputs.kms_key }}
    steps:
    
    - name: Export Config
      id: conf
      run: |
        echo "registry_uri=${{ inputs.registry_uri }}" >> $GITHUB_OUTPUT
        echo "image_uri=${{ inputs.registry_uri }}/${{ inputs.project_id }}/${{ inputs.registry_image }}" >> $GITHUB_OUTPUT
        echo "id_provider=${{ inputs.id_provider }}" >> $GITHUB_OUTPUT
        echo "service_account=${{ inputs.service_account }}" >> $GITHUB_OUTPUT
        echo "kms_key=gcpkms://${{ inputs.kms_key }}" >> $GITHUB_OUTPUT