name: image

on:
  workflow_call:
    secrets:
      registry:
        required: true
      id_provider:
        required: true
      service_account:
        required: true
    inputs:
      image:
        description: 'Image URI without the label or sha'
        required: true
        type: string
      go_version:
        description: 'Version og Go to use for tests'
        default: '1.19.4'
        required: false
        type: string
    outputs:
      digest:
        description: "Digest of the published image"
        value: ${{ jobs.image.outputs.digest }}

jobs:

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      digest: ${{ steps.image.outputs.digest }}
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}

    - run: go version

    - name: Cache Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Tidy Modules
      run: |
        make tidy

    - name: Capture Variables
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@v1
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ secrets.id_provider }}
        service_account: ${{ secrets.service_account }}

    - name: Define Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.image }}
        tags: |
          type=raw,enable=true,value=${{ env.RELEASE_VERSION }}
          type=raw,enable=true,value=${{ env.GITHUB_SHA }}

    - name: Registry Auth
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.registry }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Image Push
      id: push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Export Digest
      id: image
      run: |
        echo "digest=${{ inputs.image }}@${{ steps.push.outputs.digest }}" >> $GITHUB_OUTPUT
